openstack-cluster:
    apiServer:
        #ENC[AES256_GCM,data:6yLRohm/MZN+0BMxlOo1KN8cNNktEdJfnnXnu7J/Tkhrg7XgCZ0o/pwllgOvmk57Na+87TMj2N5JPdEAQE4Hpg==,iv:ZZY1n+A4uA6muG170H/FYBM207NgN9PPvHOvxcEQroo=,tag:rkXHyGhk22ZPSAuLtH40NA==,type:comment]
        floatingIP: ENC[AES256_GCM,data:jqDn1ACR86pfxrQ0Ajk=,iv:czMz9zdxxJg6NVF1MnqVeIm9h/YSGF8kw+lNRApbKRo=,tag:n9MFwcIkZ2C05yzq7sWxbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr298hh8ammzethfcdeh72c25wnrk3u2zlzxx78k4nfcq2rwpgqs9hljq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZDZ2K2JYQS9zUXhKMVMy
            QUNmTjBrMTAxQSszcHVZOVpPajhEVnFUdnpNCjNDeWhPT003N3NRUzhqaGl3WXFC
            WXZobzNaeDAxajRtOHhITHBRUVcyMVkKLS0tIHJadDlFdktMRjgvR3lCZTRHcWVU
            T2RjaTJVS1ZhMk9WcnZ1NS9OUkkzS1EKNHCSX6etH9qPFpuvd4FKkQcyoutxxZaz
            9GaqsYNiL+eT3uDVaz0c0+XOQs4I2m+vxR/qKlxWFHY8yJb3ZvZF3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acqcungzwkt807d3jt94ngtdt0vhk9kec4ps4a22cpaah57jw4xsl7q4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRE5zOTJoblUzb3UrWDNI
            MmFzOUVXM2Q4aE54Wk4rdjhlOUx0NjVmUHhjCko4SkJlNFRHeGlJR29uVG45UDhF
            TTMxdzRJbTM5cVM1TzlsZjVUU3RJOGsKLS0tIFZ1ZHVtTFlLWnhYMGhzY3Z0VDVC
            Mm8wZW5MRlZqckZBbjNyNmFWS3Ivbm8KCXkBaWZoK6PAGtXclJQ2brPo5ENrW4ne
            LzinpWhTIrE4S+MPWGsMfntjQt9pEzn3ZnsHAwP6yd809n6oKiAPpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h3dmygqf4v6jg3nxk5sr9jkp27w3q83sqnqxdd5n92xf3w6fs5kshakrxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZjNuYVJzOEVmM3drc09I
            cFQ2Zjg5UkRjTEllaHh6bkRncWFPdGRoNmtFCm13YmFUUFk2M2VoelhscFpPcGV2
            RnUyVDJnODg3RU5rK2JOcHZRbDZmVE0KLS0tIER0OW9iL3BSTTlQRDI5VUxkaHBn
            cmhBRlJpWjQ1RDNUOTVQS1dsNm1jWU0K9aymqXiwUC2LD3HAVD7BQA5TdhOpWMQU
            /fFy8zi8b8q+eAHDbn43zBGXcyHRMfoEvOlnMsciTqQwtJjJIygNug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRWRJM3dhS2JKS3hkTnM1
            aDY5bmFPcXpHZHJwTlJtRUdobHdvRjllbjBvCktPUXZBWWtGUmxwZm9uQmtlMU85
            SUwrTXFzUlJMSEtlRDB6YVF1NkZJd28KLS0tIEtXY1oway9GYmRraENpM2NRZzd1
            aGFuL1JlelBERGpnR25MWXBYR1hJR1kK3JaEz55tbpKkMIFcosjJWUeE+r1823yj
            UTbjq9GrCv7+5bTgYOhBbAHfT52mMSWAkCyjvji1bZrU2QbKMvEGIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16fufeddr0arrns268526gxethxgkh3g0euf8cn37kuwfmq3h23psutz4q8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEl3SXcrMGF6M296NFNv
            akJZWUFubmlzekJ3YUVVcmNwWkRibUk1aFhzCnJidGN3UVdCQ2VBUnE3TmVmWGo0
            SUw0NWU0UXRtL3RmeVEwblNRR2RvdmMKLS0tIG5vdDdkTTIzbU94b3N5UGpNcmJt
            bjRtbVA3NWhUeCthRmRmRGZaMHAyQkkKyCkvxiIw3km8bnbHa3wXS2tFo43ukPoy
            aHe/jkYh7BLKwHW5wYDfpyGx+O3pjDDo8jEqaoa9q9L11jKc2X0iKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a8e4gxw67kp27s3hssfxyem3e8jwaha3huz0sttfngeu60pk5pxqkfpg3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWmhBVVlTQi81VmpqYTJ3
            aFgzSlJxL2orVmY2Z1ZaWFR6UUYwSG82V0E0CnZRbDMrbjZuRllDUkRXNll6aXRB
            Q2E1MGJMakE1RW5ZQm51R3pNQjk0TmsKLS0tIDNEREFsLzd0anhWZWV1eC8xNk1O
            TUtadDFYelgwRnpHOW9RZVk2eWhrNDQKup4CaUmtYIXoecWgiW6qL2AwqeO2J/+u
            w5DWSCUwqQrBoQvwfZdHGo9HxOrahAPUlY+KXw/0DbGDj05fF1RrBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1drky6caal0j2x58yzpw9tyflcpdpmcjqy8nss7zfvspszg0xfpdsyzu8s4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN0ZITXBPZ3hPV05zWkxO
            ekdpbmFtOGs0TWxsQVVrR3pKblZsLzErMmlRCm1tUGp5UWdCWnMzcXV2WmhZQTF2
            UUhDSEpKendlWkozVDZ2S05sbmtMSjQKLS0tIEhacTlWVUtYZElCblNpMXowNDlN
            dStCOC9iT2lBbGJqS1crMFBqb2lEVW8KrE0LfmvsEoIkaKsZ/Nqchzb36ORRt2HP
            4ZD4DfFHY//Iog59aRl67Sz26IytZE0IDdindSWnP19FuHqrVzyFBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T15:14:09Z"
    mac: ENC[AES256_GCM,data:B+C9uAqXZBDowzgeoVV4529xAqX0AVpv4e16req/KqNkPbrDTk+kdd6oEqYcwJ04yb39/ObYY8fONB6/Uf0dfidRqevwX5JYqk0PY7ac+Y0zNYWz4UcdL4us3pcEI8PwrLhQdCD40awBDzlWPS784U5akWmRDnhs0+3nVE294n4=,iv:PN3tAmv9fzF/16cb++2pvh+VTHTvBeHDhvaD4fFfjvg=,tag:0PrFIUT+9sCUnGd9+mVM2w==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
