apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-apps
spec:
  generators:
  - git:
    repoURL: https://github.com/anish-mudaraddi/cloud-deployed-apps.git
    revision: HEAD
    files:
    - path: apps/monitoring/argocd-applications/
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        repoURL: 'https://github.com/anish-mudaraddi/cloud-deployed-apps.git'
        targetRevision: HEAD
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true