apiVersion: v1
kind: Secret
metadata:
  name: csi-manila-secret
  namespace: kube-system
type: Opaque
stringData:
    os-authURL: {{.Values.manilaCreds.OSAuthURL}}
    os-region: {{.Values.manilaCreds.OSRegion}}
    os-applicationCredentialID: {{.Values.manilaCreds.OSApplicationCredentialID}}
    os-applicationCredentialSecret: {{.Values.manilaCreds.OSApplicationCredentialSecret}}