preUpgradeChecker:
    jobEnabled: false

ingress:
  enabled: "true"
  ingressClassName: nginx
  host: longhorn.example.com
  tls: true
  secureBackends: false
  path: /

serviceMonitor:
  enabled: true

longhornManager:
  nodeSelector: 
    longhorn.store.nodeselect/longhorn-storage-node: "true"

defaultSettings:
  taintToleration: "nvidia.com/gpu:NoSchedule"
  snapshotMaxCount: 10
  snapshotDataIntegrity: true
  snapshotDataIntegtrityCronjob: true
  replicaAutoBalance: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  allowVolumeCreationWithDegradedAvailability: true

persistence:
  defaultClassReplicaCount: 3
  defaultDataLocality: disabled
  migratable: "true"