openstack-cluster:
  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.215.233"

    monitoring:
      # no need to send alerts around certs/openstack API endpoints for dev/staging clusters 
      # ends up with too many messages in the ticket queue
      blackBoxExporter: 
        enabled: false
      kubePrometheusStack:
        release:
          values:
            prometheus:
              prometheusSpec:
                externalLabels:
                  cluster: management
                  env: staging
              ingress:
                hosts:
                  - prometheus-mgmt.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - prometheus-mgmt.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana-mgmt.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - grafana-mgmt.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair
            alertmanager:
              enabled: true
              ingress:
                hosts:
                  - alertmanager-mgmt.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - alertmanager-mgmt.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair
