apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "https://github.com/DavidFair/cloud-deployed-apps.git"
    targetRevision: "prototype_folder_flows"
    path: $ENVIRONMENT/envs/$CLUSTERNAME
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
