openstack-cluster:
    apiServer:
        floatingIP: ENC[AES256_GCM,data:MsmRI2Xc5/Kpy1lT0g==,iv:plyDCV8I/kMnGwKMyhCxeAW2ilbGelDRdNn97hJIETc=,tag:DlgcCbx7kvr1C1aRNQnkAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYTB0T3VidXFSV0dtdExH
            SmdpTE14NUo1UndVVkZhK3hwdHpwZEVkUXhNCm1kMUQxS3J0VHV1eFlRM3ZGd29I
            cjJ4YlFtL3ZXUjVsaktHNGp4bzdzTFkKLS0tIEE1RC9UdkMyRHlxa0t4MVdzb2k3
            NkpIdXpGdDNPbGpuUmlVSlpPUUJETE0KDfDeJXanNQlbYTO7ce2W9L7wPh4az+sK
            Pg3E16IujqR//ysSFueF/MFGvr9A0/meqiwZIZa9PUGUmPMt3fSjwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p9q4tzawn9jh3evsgkuslklm2d4zhwhyhtcfls7n62a8cdpv8vqq7t9hqv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z3NpWnR3UEx5a0Y3QWJL
            aGVNNHNOUHdTRUh4Vlh4QldCaEFTNDlJWGp3CnBnYzBFTXZpQzg5bWF3WXA4cHpm
            SzgxeHZ2MS9HRjJKYWxRQm9Hd21WTXcKLS0tICtFUnpmQzhnMHRJYmN0K1RxR3VC
            Qm04dlRxSy9DTFhTSTBSc2VMSWlqUTgK8KI1khGK4FLYsPLcTF9HiRhQDoVJ/ew4
            LGkofZNC2NPiL1xZ816bAchNnJLciCBQz5Rf5A4xpF8uPTJ/R+nC9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T10:53:29Z"
    mac: ENC[AES256_GCM,data:sL1ss57/nWDscDDR3kJSxhSHY+J5UxwBm60LgY4upg9FNJamAgvs23Jw+6LqZK+afpoIfy6X1ztXWa7IYOrO1ovHYNokOKFLBzJsYQcZbE4Csb866U+vCgAJPkKCSH6XOwQh9pg6U2Pyif6I+HSjjVkTjU2Q4AbLlTp1Fccxx7U=,iv:4OVoQAnEDBuegfwRWV6YF/IgvWZCv3tMwj2Cq1ExSBU=,tag:7cX0vDmnkTXb6rVw4/CT5g==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
