# Log collection with fluent-bit
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: "default"
  sources:
  - repoURL: 'https://github.com/fluent/helm-charts.git'
    path: charts/fluent-operator
    targetRevision: 2.7.0
    helm:
      valueFiles:
      - ../resources/shared/fluent-bit-values.yaml
  - repoURL: 'https://github.com/anish-mudaraddi/cloud-deployed-apps.git'
    targetRevision: "main"
    ref: clusters/{{cluster}}/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fluent-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
