# Prometheus Monitoring Stack
# Alternatively, can be installed via capi-addons, once fixed
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/prometheus-community/helm-charts.git'
    path: charts/kube-prometheus-stack
    targetRevision: v0.71.2 
    helm:
      valueFiles: |
        - ../resoruces/shared/{{clusterType}}/kube-prom-stack-values.yaml

        {{ if eq .clusterName "staging-mgmt" }}
        - ../../clusters/staging-mgmt/overrides/kube-prom-stack/dev-monitoring-ingress.yaml
        {{ end }}
  
  - repoURL: 'https://github.com/anish-mudaraddi/cloud-deployed-apps.git'
    targetRevision: "main"
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
