openstack-cluster:
    addons:
        monitoring:
            kubePrometheusStack:
                release:
                    values:
                        alertmanager:
                            config:
                                global:
                                    smtp_smarthost: ENC[AES256_GCM,data:aMmisfYTuR5uT6UsxArbGyKONgI=,iv:qLMJvmicy0b3TZvO8gUJEnuy6FyInjApuTRUEnVcScQ=,tag:/ovnhYiT8H+PQpi3ei8wzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWmd0c0krY1hRRFVNZDJz
            bC9jcmlxNC9ET2FtNDkrL25WR09EbVg4b1MwCm1hdUNVSnBSd1h5UW1PU2c1RG5R
            amdnV2tockJEMW53bHF2ODBnd1pBZzgKLS0tIE1UUEg5RzdpRlJSdzR4Q2s5RlNQ
            MWg3a2pya0k2SnpnZTc5LzlMV3JMdzQKFV1yxTLroCDJJCeSuOHIOF6ja0jW11CP
            Qa+ZQ2FEYEbgUEkmjYpUj33XUpdB013UNR8ZPCZ9eROIcaJp/Daw8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p9rynn6rcdfhx0kdks0sh5drjrjg857cuujapu04m9a2r0zarq6stdha6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWGozT1FzbHJicXhvb2Jv
            TnRTcWRwZVNQVUprNDdLQW9lUHM0QWh3TkdnCldtbEdoTU5zRkc1VnppTGFCQXNt
            azR3cDU4N3pCRlZTaHZUajcrWFRrV2sKLS0tIGt5RWdlRVVzWHNrMjY0clF2U2R3
            MlhsUTdUeUtGMStzN1FZL2xmYnBHTE0KXEJCBSTSAilBEgnxljBiKLvCzi7wLdi7
            JfEO29Xnw+0VuB36cNHZ46wlH7tHquICgHrd7Clfu/X6Jj3XUIdqhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T09:01:23Z"
    mac: ENC[AES256_GCM,data:ovhE3Zub75CKbeXzmI9ftvfwNHhAOQJHYmKwls1VF0DAmwt8KR4RF61U1+2PNB2+RGVVg5z65qttIPKuHlRVuc9o11C2dERdRbtsEaXXJxnrSRdZbA3u409fxLi+qGqYyk21JAUp3RdQxtZ4C1n/GkguNu4ZpIP/wsqWjlKfc/A=,iv:hNw4JpVonX677UTkR3ITWZea5jfchVBkCcLV9tmaLfM=,tag:y7pmIrd657ZXg4fSSaG8Mg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
