
fluentbit:
  enable: true
  resources:
    limits:
      cpu: 500m
      memory: 400Mi
    requests:
      cpu: 10m
      memory: 25Mi
  annotations:
    fluentbit.io/exclude: "true"
    promtheus.io/scrape: "true"

  additionalVolumes:
    - name: host-proc
      hostPath:
        path: /proc/
    - name: host-sys
      hostPath:
        path: /sys/
    - name: host-buffer
      hostPath:
        path: /tmp/fluent-bit-buffer
  additionalVolumesMounts:
    - mountPath: /host/sys
      mountPropagation: HostToContainer
      name: host-sys
      readOnly: true
    - mountPath: /host/proc
      mountPropagation: HostToContainer
      name: host-proc
      readOnly: true
    - mountPath: /host/fluent-bit-buffer
      mountPropagation: HostToContainer
      name: host-buffer

  input:
    tail:
      enable: true
    systemd:
      enable: true
    nodeExporterMetrics:
      tag: node_metrics
      scrapeInterval: 15s
      path:
        procfs: /proc/
        sysfs: /sys/
    fluentBitMetrics:
      scrapeInterval: 10s
      scrapeOnStart: true
      tag: "fb.metrics"

  output:
    opensearch:
      host: opensearch.stfc.ac.uk
      port: 9200
      httpPassword:
        valueFrom:
          secretKeyRef:
            name: opensearch-credentials
            key: password
      httpUser:
        valueFrom:
          secretKeyRef:
            name: opensearch-credentials
            key: username
      index: kube_logs_{{ .Values.global.env }}_{{ .Values.global.clusterName }}
      logstashFormat: On
      logstashPrefix: node
      replaceDots: true
      type: flb_type
      traceError: true
      suppressTypeName: On
      timeKey: "@timestamp"
      tls:
        verify: false

    prometheusMetricsExporter:
      metricsExporter:
        host: "0.0.0.0"
        port: 2020
        addLabels:
          app: "fluentbit"

    loki:
      enable: false
      host:
      port: 3100

      httpUser:
        valueFrom:
          secretKeyRef:
            key: value
            name: husersecret
      httpPassword:
        valueFrom:
          secretKeyRef:
            key: value
            name: hpasssecret
      tenantID:
        valueFrom:
          secretKeyRef:
            key: value
            name: tenantsecret
      tls: {}
  service:
    storage:
      path: "/host/fluent-bit-buffer/"
      backlogMemLimit: "50MB"
      checksum: "off"
      deleteIrrecoverableChunks: "on"
      maxChunksUp: 128
      metrics: "on"
      sync: normal

  filter:
    kubernetes:
      enable: true
      label: false
    containerd:
      enable: true
    systemd:
      enable: true

fluentd:
  enable: false
