openstack-cluster:
  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.211.178"

    monitoring:
      kubePrometheusStack:
        release:
          values:
            prometheus:
              prometheusSpec:
                externalLabels:
                  cluster: management
                  env: dev
              ingress:
                hosts:
                  - prometheus.dev-mgmt.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - prometheus.dev-mgmt.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana.dev-mgmt.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - grafana.dev-mgmt.nubes.stfc.ac.uk
                    secretName: tls-keypair
            alertmanager:
              enabled: true
              ingress:
                hosts:
                  - alertmanager.dev-mgmt.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - alertmanager.dev-mgmt.nubes.stfc.ac.uk
                    secretName: tls-keypair
