{{- if .Values.apps -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec: 
  generators:
    - list:
        elements: 
        {{- toYaml .Values.apps | indent 10 }}
  project: {{ $.Values.global.project }}
  destination:
    namespace: clusters
    server: https://kubernetes.default.svc

  template:
    metadata:
      name: "{{ .name }}-cluster"
      # All applications need to go into the ArgoCD namespace
      namespace: argocd
    spec:
      project: {{ $.Values.global.project }}
      sources:
        # chart to read from
        - repoURL: {{ default (index $.Values.appDefaults .chartName).chartRepo .chartRepo }}
          targetRevision: {{ default (index $.Values.appDefaults .chartName).chartVersion .chartVersion }}
          chart: {{ default (index $.Values.appDefaults .chartName).chartName .chartName }}
            helm:
              valueFiles:
                {{- range $chartName, $filenames := $.Values.valueFiles }}
                {{- if eq $chartName .chartName }}
                {{- range $filename := $filenames }}
                - $local_vals/{{ $.Values.global.environment }}/apps/{{ .name }}/{{ $filename }}
                {{- end }}
                {{- end }}
                {{- end }}

                {{- if .additionalValueFiles }}
                {{- range $filename := .additionalValueFiles }}
                - $local_vals/{{ $.Values.global.environment}}/envs/{{ $.Values.cluster.clusterName }}/{{ $filename }}
                {{- end }}
                {{- end }}
                
              {{- if .additionalValues }}
              values:
                {{- toYaml .additionalValues | indent 10 }}
              {{ end }}

        # values files to track 
        - repoURL: {{ $.Values.global.repoURL }}
          targetRevision: {{ default $.Values.global.targetRevision .targetRevision }}
          ref: local_vals
    
  syncPolicy:
    {{- if not .disableAutomated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
