apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "cluster-addons-app"
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://stackhpc.github.io/cluster-api-addon-provider
    chart: cluster-api-addon-provider
    targetRevision: 0.5.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
