apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.project }}
  source:
    repoURL: {{ $.Values.global.repoURL }}
    targetRevision: {{ $.Values.global.targetRevision }}
    path: charts/{{ $.Values.global.environment }}/deps/argocd
    {{- if (index $.Values "argo-cd") }}
    helm:
      values: 
{{ toYaml (index $.Values "argo-cd") | indent 8 }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
