apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.project }}
  source:
    repoURL: {{ $.Values.global.repoURL }}
    targetRevision: {{ $.Values.global.targetRevision }}
    path: charts/{{ $.Values.global.environment }}/deps/argocd-apps
    helm:
      valueFiles:
        - ./values.yaml
        - ../../../../envs/{{ $.Values.global.environment }}/app-values.yaml
        - ../../../../envs/{{ $.Values.global.environment }}/{{ $.Values.clusterName }}/app-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
