openstack-cluster:
    addons:
        monitoring:
            kubePrometheusStack:
                release:
                    values:
                        alertmanager:
                            config:
                                global:
                                    smtp_smarthost: ENC[AES256_GCM,data:2bvYSHWxPmCA+KO5ujJdHSzKW8A=,iv:ba+af4K8NgbE6p+alFs4tC6Hrk98BsHhCFWn0L3Hf1E=,tag:f5uVplI0QH3j0Y/u1+/CRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr298hh8ammzethfcdeh72c25wnrk3u2zlzxx78k4nfcq2rwpgqs9hljq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMmJoYnRqQzJqME5KTEdQ
            NnZDSFFSb1B2Tnl5VFBEWHc5MEJVY0pkU2xrCit4UFVKcStWMEFsYUxwL095dVBS
            d1R3K3dpa1gyQjBCaFZhb3RyYWxXcGMKLS0tIGx3cndrOTM4emg3ZSs2N05taEFG
            ME51dDVCOXhrdnU3NFdMS1p1UUpKVTgKESdjW9smvLNpNeqVNYivqZyC46IeMz3O
            LeSsmRIcQjm4qj/9wya2fGbZBQUcKiYgQm42/stdoIvPISUju0mkkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acqcungzwkt807d3jt94ngtdt0vhk9kec4ps4a22cpaah57jw4xsl7q4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMjdkZm5CL1kxakgwcytX
            SW5sbktvdDA2cU5VbjBqTlczTVhIeSsvV0Q4CjFyTDVBdEx3YXZIL1NUZkx6eklL
            OW00QjVBcGdlcmlJdXlUY1RGZWJPTkUKLS0tIEppdHRlZFlQNkhteEVmOVQrMXNR
            NVhIVFdWTmx0WXlIZmNhdGxSMG53eWsKxg6TvuYdQ7TnZBFgn7SZB86tiszbF27k
            DZdigsBGrkd100kzwxo+FUau2Sp2/TcJFydHMCTIqixcpQq+AoUBBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h3dmygqf4v6jg3nxk5sr9jkp27w3q83sqnqxdd5n92xf3w6fs5kshakrxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOFdOVHZ4bm9uWHViL0Iy
            aDJWMFhUYkwvcXhaV1IxOForYU5jRHl4cEg4CnAyMzh1azRyQUNvOGxiKzlNUDdy
            UzduWEtNMEpCQlowQjZPMnE2SVlOZDQKLS0tICtuTnBZcUlYZTUzZmlqamUyNlc4
            NnVXWnF6OUxxKzRHek9FRUVVbVM0THMKrggfYnF32sS6SRsuRDAbexAOvrGQH5bf
            Uv+W82Wyz0nlY3M7gpuvAAjkkyALUP60YdjFJIr+mVr1kaagZmoAQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGY2SXh4ZkIzUGtqQnhm
            WGdQS25xRGs3czNuOGtJM0pOZ1gvYk54NGo0CjBsTEk4b1BHRENaRWR3Wnhzcndj
            bXZaZ0l0d3gxWVF6RGZhUTVGbStzZzgKLS0tIG1lV0RMc0NmbjNYWFZwSVFmdHVC
            aG9GdXlrSE9TV2k1VFdrb2IzdmVNemMKkdA5kB7pG4xMPE/iqVg/WacUwyFyaNcl
            R3UpXUbMHP6C0xpZ4QvV4YtzK88M1XPrfYASVzXcGdv6o5ckR6O4Tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16fufeddr0arrns268526gxethxgkh3g0euf8cn37kuwfmq3h23psutz4q8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDU0hyTDhwMXQ0aWJDdC83
            TlFDOTZVa2pkTEJUWU4zcDlhM1pKaGp5b0JnCkM1WTFFNlUyMFArTncvbTZqKzk2
            RUY5Z1FRQ3lVMlQrOVpMbVBNclpoZlkKLS0tIG43eVJMMGttR0RIcHJqUDFIbUh2
            KzBYK1MvbXZyQjFud1lIUGVQY2lWaEUK2w9htvG+6SqPR193HoXAVmElnilOIaiU
            6t3a8YN5c7ghKKONvPQ4w16Giy3nRJUn/mDHBTLg0bG3aqOL3LbfHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a8e4gxw67kp27s3hssfxyem3e8jwaha3huz0sttfngeu60pk5pxqkfpg3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK0dIdGNlMlpKUnFhTUhs
            ZUdmcFFjUy95MDdtT2ZPUVhhTkRVbDJXbVNNCi9VYitVTi9YZ2wyNzdNeUdXNy9T
            d1pzMVJCdTdScTIxYk9KeG9lQmtJcEEKLS0tIGhCSk1ZbCt2cGkvQUVGMC9nL2lv
            RHFpU1NBWDlBQm43clU1dUNHQXg2WU0KAv7s9qmozerkuugwJsneHX4UbluGcuVO
            ykYRbA+1ZsFi5PjOIz2IsRTOuiPDAZQ7L5h/89vDtTqlUqjXleSuFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1drky6caal0j2x58yzpw9tyflcpdpmcjqy8nss7zfvspszg0xfpdsyzu8s4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYjNNVC9uTElwbEowOUNB
            N2xuZDI2Ym5Ob0NQVVc1OVVIZU5wTktpYmpFCnJjRTFBeGh2R3Q4Q3FJL25HZXVj
            OUhidzVkS3JrZCtjOHpKZGprU1RiTzQKLS0tIDd5cW81VXVzeHhOOUprYlpOT1pQ
            UnV4c2lyYVVsWmZIcmlxcVdiRDZGQmMKjN8evAGPXQ956SzwMuNal0KXKQeVIcB6
            CDVwhY1/XYHoFCWAKdkBaCMpcjot3GRzr6MQgO2Rq5NoJEXT+5SAsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T08:46:49Z"
    mac: ENC[AES256_GCM,data:L3haNP2GWwpJGWVipDDrmtCLBEWb0uOPUfvhC9TZrgI2pHkfxXFTY5BJOuesrJYvyeabJjdOk4E4lxxRF5h9BaLekyANlqJvyBK74KqQb6N8wFjmGdFaY8pJasu/qPt9aOQuIhzXLSmTkNBlCDLmVYftSFyQTUjvXm8VtOW9Yc4=,iv:JsNgngD4/F3oAp3MsA0AzfrUJIlFTnLxESusc3+zpJ0=,tag:UHzCd3Pc/NeEjoIpAOF3LQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
