apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.image.tag }}

  selector:
    matchLabels:
      app: {{ .Values.app }}

  template:
    metadata:
      labels:
        app: {{ .Values.app }}

    spec:
      containers:
      - name: {{ .Values.app }}
        image: harbor.stfc.ac.uk/{{ .Values.image.project }}/cloud-chatops:{{ .Values.image.tag }}
        volumeMounts:
        - name: cloud-chatops-config
          mountPath: /usr/src/app/cloud_chatops/config
          readOnly: true
        - name: cloud-chatops-secrets
          mountPath: /usr/src/app/cloud_chatops/secrets
          readOnly: true

      volumes:
      - name: cloud-chatops-config
        configMap:
          name: {{ .Values.env }}-cloud-chatops-config
          items:
          - key: "config.yml"
            path: "config.yml"
      - name: cloud-chatops-secrets
        secret:
          secretName: {{ .Values.env }}-cloud-chatops-secrets


