argo-cd:
  global:
    domain: argocd.staging-worker.nubes.stfc.ac.uk
  
longhorn:
  ingress:
    host: "longhorn.staging-worker.nubes.stfc.ac.uk"
  persistence:
    # can't be set for RWX
    migratable: false