openstack-cluster:

  nodeGroups:
    - name: default-md-0
      machineCount: 5

  nodeGroupDefaults:
    machineFlavor: l3.nano
    nodeLabels:	
      # we're running longhorn on this cluster
      # set label so worker nodes can host longhorn volumes
      longhorn.store.nodeselect/longhorn-storage-node: true

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.81.242"

    monitoring:
      # no need to send alerts around certs/openstack API endpoints for dev/staging clusters 
      # ends up with too many messages in the ticket queue
      blackBoxExporter: 
        enabled: false
      kubePrometheusStack:
        release:
          values:
            prometheus:
              prometheusSpec:
                externalLabels:
                  cluster: worker
                  env: staging
              ingress:
                hosts:
                  - prometheus-worker.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - prometheus-worker.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana-worker.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - grafana-worker.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair
            alertmanager:
              enabled: true
              ingress:
                hosts:
                  - alertmanager-worker.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - alertmanager-worker.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair