openstack-cluster:

  nodeGroups:
    - name: default-md-0
      machineCount: 5

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.81.242"

    monitoring:
      kubePrometheusStack:
        release:
          values:
            prometheus:
              prometheusSpec:
                externalLabels:
                  cluster: worker
                  env: staging
              ingress:
                hosts:
                  - prometheus-worker.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - prometheus-worker.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana-worker.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - grafana-worker.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair
            alertmanager:
              enabled: true
              ingress:
                hosts:
                  - alertmanager-worker.staging.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - alertmanager-worker.staging.nubes.stfc.ac.uk
                    secretName: tls-keypair