name: Promote Dev to Staging

on:
  schedule:
    - cron: '0 12 * * 2'  # Tuesday at 12pm UTC
  workflow_dispatch:

jobs:
  create-promotion-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set branch and PR names
        id: env-vars
        run: |
          echo "branch_name=dev-to-staging-${{ steps.date.outputs.date }}" >> $GITHUB_OUTPUT
          echo "pr_title=Promote Dev to Staging - ${{ steps.date.outputs.date }}" >> $GITHUB_OUTPUT

      - name: Check for changes
        id: check-changes
        run: |
          if diff -r charts/dev charts/staging > /dev/null; then
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Promote Changes
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: |
          rm -rf charts/staging
          cp -r charts/dev charts/staging

      - name: Commit and Create Pull Request
        if: steps.check-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "${{ steps.env-vars.outputs.pr_title }}"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: "${{ steps.env-vars.outputs.branch_name }}"
          delete-branch: true
          title: ${{ steps.env-vars.outputs.pr_title }}
          body: |
            Automated promotion PR to copy contents from `dev` to `staging`.
            
            This PR was automatically created by the environment promotion workflow.
          base: main
          labels: |
            automated
            environment-promotion

      - name: Log no changes
        if: steps.check-changes.outputs.changes_detected == 'false'
        run: echo "No changes detected between dev and staging. Skipping PR creation."